"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Created by lifeg on 5/2/2017.
 */
var UnicodeScript;
(function (UnicodeScript) {
    UnicodeScript.Arabic = "Arabic";
    UnicodeScript.Armenian = "Armenian";
    UnicodeScript.Balinese = "Balinese";
    UnicodeScript.Bamum = "Bamum";
    UnicodeScript.Batak = "Batak";
    UnicodeScript.Bengali = "Bengali";
    UnicodeScript.Bopomofo = "Bopomofo";
    UnicodeScript.Braille = "Braille";
    UnicodeScript.Buginese = "Buginese";
    UnicodeScript.Buhid = "Buhid";
    UnicodeScript.CanadianAboriginal = "CanadianAboriginal";
    UnicodeScript.Cham = "Cham";
    UnicodeScript.Cherokee = "Cherokee";
    UnicodeScript.Common = "Common";
    UnicodeScript.Coptic = "Coptic";
    UnicodeScript.Cyrillic = "Cyrillic";
    UnicodeScript.Devanagari = "Devanagari";
    UnicodeScript.Ethiopic = "Ethiopic";
    UnicodeScript.Georgian = "Georgian";
    UnicodeScript.Glagolitic = "Glagolitic";
    UnicodeScript.Greek = "Greek";
    UnicodeScript.Gujarati = "Gujarati";
    UnicodeScript.Gurmukhi = "Gurmukhi";
    UnicodeScript.Han = "Han";
    UnicodeScript.Hangul = "Hangul";
    UnicodeScript.Hanunoo = "Hanunoo";
    UnicodeScript.Hebrew = "Hebrew";
    UnicodeScript.Hiragana = "Hiragana";
    UnicodeScript.Inherited = "Inherited";
    UnicodeScript.Javanese = "Javanese";
    UnicodeScript.Kannada = "Kannada";
    UnicodeScript.Katakana = "Katakana";
    UnicodeScript.KayahLi = "KayahLi";
    UnicodeScript.Khmer = "Khmer";
    UnicodeScript.Lao = "Lao";
    UnicodeScript.Latin = "Latin";
    UnicodeScript.Lepcha = "Lepcha";
    UnicodeScript.Limbu = "Limbu";
    UnicodeScript.Lisu = "Lisu";
    UnicodeScript.Malayalam = "Malayalam";
    UnicodeScript.Mandaic = "Mandaic";
    UnicodeScript.MeeteiMayek = "MeeteiMayek";
    UnicodeScript.Mongolian = "Mongolian";
    UnicodeScript.Myanmar = "Myanmar";
    UnicodeScript.NewTaiLue = "NewTaiLue";
    UnicodeScript.Nko = "Nko";
    UnicodeScript.Ogham = "Ogham";
    UnicodeScript.OlChiki = "OlChiki";
    UnicodeScript.Oriya = "Oriya";
    UnicodeScript.PhagsPa = "PhagsPa";
    UnicodeScript.Rejang = "Rejang";
    UnicodeScript.Runic = "Runic";
    UnicodeScript.Samaritan = "Samaritan";
    UnicodeScript.Saurashtra = "Saurashtra";
    UnicodeScript.Sinhala = "Sinhala";
    UnicodeScript.Sundanese = "Sundanese";
    UnicodeScript.SylotiNagri = "SylotiNagri";
    UnicodeScript.Syriac = "Syriac";
    UnicodeScript.Tagalog = "Tagalog";
    UnicodeScript.Tagbanwa = "Tagbanwa";
    UnicodeScript.TaiLe = "TaiLe";
    UnicodeScript.TaiTham = "TaiTham";
    UnicodeScript.TaiViet = "TaiViet";
    UnicodeScript.Tamil = "Tamil";
    UnicodeScript.Telugu = "Telugu";
    UnicodeScript.Thaana = "Thaana";
    UnicodeScript.Thai = "Thai";
    UnicodeScript.Tibetan = "Tibetan";
    UnicodeScript.Tifinagh = "Tifinagh";
    UnicodeScript.Vai = "Vai";
    UnicodeScript.Yi = "Yi";
})(UnicodeScript = exports.UnicodeScript || (exports.UnicodeScript = {}));
//# sourceMappingURL=scripts.js.map